# 1. Используем node для сборки Vue-приложения
FROM node:18 AS builder

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package.json package-lock.json ./
RUN npm install

# Копируем весь код и собираем проект
COPY . .
RUN npm run build

# 2. Используем Nginx для раздачи готового Vue-приложения
FROM nginx:1.23

# Копируем собранное приложение в Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем кастомный конфиг для Nginx (если нужно)
COPY nginx.conf /etc/nginx/nginx.conf

# Открываем порт 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
