version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://maglev.proxy.rlwy.net:17352/railway
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=buLYnDObTGrXXodtVLpHCktgmqObMuwp
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontapp:
    build:
      context: ./frontend
      dockerfile: dockerfile
      target: production-stage
    ports:
      - "3000:3000"
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontapp
      - app
      - db

volumes:
  postgres-data:
